[project]
name = "open-super-whisper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.5",
    "openai>=1.75.0",
    "pynput>=1.8.1",
    "pyqt6>=6.9.0",
    "sounddevice>=0.5.1",
    "soundfile>=0.13.1",
]
